baseURL: "https://mi-ki-ri.github.io/"
languageCode: "en-us"
title: "RePortfolio"
theme: "reportfolio"
taxonomies:
  tag: "tags"

publishDir: "docs"

mediaTypes:
  application/json:
    suffixes: json

outputFormats:
  json:
    MediaType: application/json
    noUgly: true

outputs:
  home: [HTML, JSON, RSS]
