baseURL: "http://example.org/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "reportfolio"
taxonomies:
  tag: "tags"

mediaTypes:
  application/json:
    suffixes: json

outputFormats:
  json:
    MediaType: application/json
    noUgly: true

outputs:
  home: [HTML, JSON, RSS]
